hw2
bifidok/TinkoffBackend pull request #2
Opened 2024-02-21 13:37 UTC by bifidok

2024-02-29 16:29 UTC, x1vr64 requested changes
В целом ДЗ сделана, но не хватает работающих тестов (запуск тестов на проекте не должен предпологать ручных действий и секретов), Мы поднимаем нужное окружение в тесте и проверяем на нем. Pipeline должен проходить, покрытие нужно держать на уровне.

2024-02-29 16:29 UTC, x1vr64 commented on .gitignore
> +application-test.yml
А зачем добавлять application-test в игнор и удалять application.yml? Сейчас, чтобы запустить тесты, надо руками добавлять файл, что в ci/cd будет очень неудобно делать.

2024-02-29 16:29 UTC, x1vr64 commented on scrapper/src/main/java/edu/java/dto/RepositoryResponse.java
> +                                 @JsonProperty("updated_at") String lastActivity) {
В требованиях к домашнему заданию был пункт с хранением даты

> В *Response-классах для хранения времени должен использоваться класс OffsetDateTime.

Не получилось в случае с гитхабом?

2024-02-29 16:29 UTC, x1vr64 commented on scrapper/src/test/java/edu/java/scrapper/clients/GitHubClientTest.java
> +    public WireMockRule wireMockRule = new WireMockRule();
RuleWith и Rule и Test это junit4. SpringBootTest использует апи junit 5. Смешались junit 4 и junit 5. Давай все сделаем на 5й версии.

2024-03-01 11:47 UTC, bifidok commented
Не понимаю как правильно мержить в основную ветку при такой ситуации? Не трогать hw2 и замержить с hw3? И нужно ли делать теперь изменения в hw3(готов pull request)?
![image](https://github.com/bifidok/TinkoffBackend/assets/16528008/bf36f6a5-0364-4867-b244-4203e383f7c4)

2024-03-04 10:55 UTC, bifidok commented
Теперь так. Скоро будет выглядеть еще хуже. Как тут быть?
![image](https://github.com/bifidok/TinkoffBackend/assets/16528008/5d63011c-bd02-43db-97d7-bf9a6742f94d)

2024-03-09 09:55 UTC, x1vr64 commented
> Теперь так. Скоро будет выглядеть еще хуже. Как тут быть?

Все не так плохо) Буду разгребать активнее

2024-03-09 09:55 UTC, x1vr64 approved these changes

2024-04-15 01:48 UTC, closed without merging