Hw3
bifidok/TinkoffBackend pull request #3
Opened 2024-02-28 13:37 UTC by bifidok

2024-03-09 18:51 UTC, x1vr64 requested changes
Надо бы привнести изменения из 2го ДЗ.
Тесты, на работу наших клиентов тоже надо сделать. Больше внимания уделять расположению классов в прокте.

2024-03-09 18:51 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/clients/ScrapperClient.java
> +    HttpStatus removeLink(@PathVariable("id") int tgChatId, @RequestBody RemoveLinkRequest removeLinkRequest);
По описанию, которое надо было реализовать, у нас телеграм id должен находиться в заголовках запроса

2024-03-09 18:51 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/controllers/UpdateController.java
> +        }
Так можно делать, но рекомендую почитать про https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-validation.html. Этот подход позволяет описывать все обязательные поля в самой DTO

2024-03-09 18:51 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/configurations/ClientConfig.java
> +@ConfigurationProperties
`@ConfigurationProperties` используется для обозначения класса с пропертями. Замени эту аннотацию на `@Configuration` и убери его из `BotApplication`

2024-03-09 18:51 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/configurations/WebConfig.java
> +    }
Корс? Без него не заводился сваггер?

2024-03-09 18:51 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/dto/ApiErrorResponse.java
> +    private final StackTraceElement[] stackTrace;
Этот массив должен быть массивом строк

2024-03-09 18:51 UTC, x1vr64 commented on .gitignore
> +application-test.yml
Зачем добавлять тестовую конфигурацию в игнор?

2024-03-09 18:51 UTC, x1vr64 commented on scrapper/src/main/resources/application.yml
> -  config: classpath:log4j2-plain.xml
Тут нет никаких секретов, почему мы удаляем этот файл? Нам он пригодится для запуска приложения

2024-03-09 18:51 UTC, x1vr64 commented on scrapper/src/main/java/edu/java/scrapper/controllers/LinkController.java
> +            .toList();
Обработку запроса от пользователя надо вынести в отдельный класс. Сейчас контроллеры делают слишком много

2024-03-09 18:51 UTC, x1vr64 commented on scrapper/src/main/java/edu/java/scrapper/dto/RepositoryResponse.java
> +                                 @JsonProperty("updated_at") String lastActivity) {
Как я понимаю, это с старого коммита была основа. Надо тут тоже поправить на `OffsetDateTime`

2024-03-09 18:51 UTC, x1vr64 commented on scrapper/src/main/java/edu/java/scrapper/ExceptionApiHandler.java
> +public class ExceptionApiHandler {
Давай перенесем этот класс к контроллерам ближе

2024-03-09 18:51 UTC, x1vr64 commented on scrapper/src/main/java/edu/java/scrapper/LinkUpdaterScheduler.java
> +public class LinkUpdaterScheduler {
Шедулер тоже в свой пакет

2024-03-09 18:51 UTC, x1vr64 commented on scrapper/src/test/java/edu/java/scrapper/clients/GitHubClientTest.java
> +public class GitHubClientTest {
Вообщем да, надо бы залить все изменения из 2й ДЗ в эту ветку.

2024-03-09 18:51 UTC, x1vr64 commented on scrapper/src/main/java/edu/java/scrapper/models/Link.java
> +        return Objects.hash(link);
Аннотация `@Data` уже предоставляет реализацию equals и hashcode.

2024-03-10 05:21 UTC, bifidok commented on bot/src/main/java/edu/java/bot/configurations/WebConfig.java
> +    }
Да, запросы из swagger editor не работали

2024-03-10 05:26 UTC, bifidok commented on scrapper/src/main/java/edu/java/scrapper/controllers/LinkController.java
> +            .toList();
В следующих дз вся логика из контроллеров вынесена в сервисы.

2024-03-17 17:30 UTC, x1vr64 approved these changes
Все еще есть проблемы с реализуемым контрактом.
Запусти приложение scrapper и перейди по ссылке http://localhost:8080/swagger-ui/index.html. Там ты увидишь, что название твоего заголовка отличается от указанного в задаче

2024-03-17 17:30 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/clients/ScrapperClient.java
> +    HttpStatus removeLink(@RequestHeader int tgChatId, @RequestBody RemoveLinkRequest removeLinkRequest);
Я не уверен, что заголовок будет правильно называться. А в тесте мы это не проверяем также

2024-03-17 17:30 UTC, x1vr64 commented on scrapper/src/test/java/edu/java/scrapper/clients/StackOverflowClientTest.java
> +        LocalDateTime dateTime = LocalDateTime.MIN;
у тебя в моке дата отдается как -31557014135596800. Лучше использовать понятную существующую дату

2024-03-17 17:30 UTC, x1vr64 commented on scrapper/src/test/java/edu/java/scrapper/clients/BotClientTest.java
> +        HttpStatus status = botClient.checkUpdate(linkUpdateRequest);
Почему мы проверяем на null? Это ожидаемое поведение?

2024-03-17 17:30 UTC, x1vr64 commented on bot/src/test/java/edu/java/bot/clients/ScrapperClientTest.java
> +        HttpStatus status = scrapperClient.addLink((int) DEFAULT_CHAT_ID, new AddLinkRequest(URI.create("http://localhost")));
У нас часть параметров, это заголовок клиента, но мы его тут не проверяем. Наши тесты бы помогли отловить ошибку разработки.

2024-04-15 01:49 UTC, merged